# Form implementation generated from reading ui file 'input.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1500, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../resources/stc_logo.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(132, 132, 132);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.inputWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.inputWidget.setStyleSheet(
            "QTableWidget{\n"
            "color:black;\n"
            "            background: white;\n"
            "selection-background-color:#0090c4;\n"
            "border:none;\n"
            "border-bottom:1px solid black;\n"
            " gridline-color:black;\n"
            "border-left:1px solid black;\n"
            "border-right:1px solid black;\n"
            "}\n"
            "QComboBox{\n"
            "    border:                 none;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "color:                      rgb(13, 13, 13);\n"
            "    font-weight:            bold;\n"
            "    padding:                    5px;\n"
            "\n"
            "}\n"
            "QComboBox:selected{\n"
            "   \n"
            "    background-color: rgb(0, 144, 196);\n"
            "color:                      rgb(13, 13, 13);\n"
            "}\n"
            "\n"
            "QHeaderView{\n"
            "    background-color: white;\n"
            '    font: 700 9pt "Segoe UI";\n'
            "}\n"
            "QHeaderView::section{\n"
            "background-color: rgb(220, 220, 220);\n"
            "border:0.5px solid black;\n"
            "border-left:none;\n"
            "}"
        )
        self.inputWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.inputWidget.setAlternatingRowColors(True)
        self.inputWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.inputWidget.setShowGrid(True)
        self.inputWidget.setCornerButtonEnabled(False)
        self.inputWidget.setRowCount(25)
        self.inputWidget.setColumnCount(11)
        self.inputWidget.setObjectName("inputWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(
            QtCore.Qt.ItemFlag.ItemIsSelectable
            | QtCore.Qt.ItemFlag.ItemIsUserCheckable
            | QtCore.Qt.ItemFlag.ItemIsEnabled
        )
        self.inputWidget.setItem(0, 0, item)
        self.inputWidget.horizontalHeader().setMinimumSectionSize(30)
        self.inputWidget.verticalHeader().setVisible(True)
        self.inputWidget.verticalHeader().setDefaultSectionSize(25)
        self.inputWidget.verticalHeader().setHighlightSections(True)
        self.inputWidget.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_2.addWidget(self.inputWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "INPUT FILE PREVIEW"))
        __sortingEnabled = self.inputWidget.isSortingEnabled()
        self.inputWidget.setSortingEnabled(False)
        self.inputWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
