# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 750)
        Form.setMaximumSize(QtCore.QSize(800, 750))
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 751))
        self.frame.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.frame.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.frame.setStyleSheet(
            "\n" "background-color:rgba(32,33,36,255);\n" "color:white;"
        )
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(330, 90, 91, 91))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("stc_logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(270, 180, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(parent=self.frame)
        self.username.setEnabled(True)
        self.username.setGeometry(QtCore.QRect(120, 290, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(False)
        self.username.setFont(font)
        self.username.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.username.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding-left:10px;\n"
            "background-color: rgba(63,64,66,255)\n"
            "\n"
            "}"
        )
        self.username.setText("")
        self.username.setCursorPosition(0)
        self.username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username.setDragEnabled(True)
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=self.frame)
        self.password.setGeometry(QtCore.QRect(120, 373, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password.setFont(font)
        self.password.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.password.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding:5px;\n"
            "    background-color:rgba(63,64,66,255)\n"
            "}"
        )
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(127, 433, 131, 16))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.btn_signup = QtWidgets.QPushButton(parent=self.frame)
        self.btn_signup.setGeometry(QtCore.QRect(240, 430, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_signup.setFont(font)
        self.btn_signup.setStyleSheet(
            "QPushButton{\n" "border:none;\n" "color:white;\n" "}"
        )
        self.btn_signup.setObjectName("btn_signup")
        self.btn_login = QtWidgets.QPushButton(parent=self.frame)
        self.btn_login.setGeometry(QtCore.QRect(460, 500, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet(
            "QPushButton{\n"
            "\n"
            "    background-color:rgba(63,64,66,255);\n"
            "border:2px solid black;\n"
            "border-radius:10px;\n"
            "color:white;\n"
            "\n"
            "}\n"
            "QPushButton:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "color:white;\n"
            "border:2px solid black;\n"
            "}"
        )
        self.btn_login.setObjectName("btn_login")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.username, self.password)
        Form.setTabOrder(self.password, self.btn_login)
        Form.setTabOrder(self.btn_login, self.btn_signup)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Login"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.password.setPlaceholderText(_translate("Form", "Password"))
        self.label_3.setText(_translate("Form", "Didn't Have Account?"))
        self.btn_signup.setText(_translate("Form", "Click Here"))
        self.btn_login.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
