# Form implementation generated from reading ui file 'signup.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 750)
        Form.setMaximumSize(QtCore.QSize(800, 750))
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 781, 731))
        self.frame.setStyleSheet("\nbackground-color:rgba(32,33,36,255);\ncolor:white;")
        self.frame.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(320, 50, 91, 91))
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("stc_logo.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(250, 150, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.username = QtWidgets.QLineEdit(parent=self.frame)
        self.username.setGeometry(QtCore.QRect(130, 240, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.username.setFont(font)
        self.username.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding-left:10px;\n"
            "background-color: rgba(63,64,66,255)\n"
            "\n"
            "}"
        )
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.re_password = QtWidgets.QLineEdit(parent=self.frame)
        self.re_password.setGeometry(QtCore.QRect(130, 450, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.re_password.setFont(font)
        self.re_password.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding-left:10px;\n"
            "background-color: rgba(63,64,66,255)\n"
            "\n"
            "}"
        )
        self.re_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.re_password.setClearButtonEnabled(True)
        self.re_password.setObjectName("re_password")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(135, 513, 121, 16))
        self.label_3.setObjectName("label_3")
        self.btn_signup = QtWidgets.QPushButton(parent=self.frame)
        self.btn_signup.setGeometry(QtCore.QRect(250, 510, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_signup.setFont(font)
        self.btn_signup.setStyleSheet("QPushButton{\nborder:none;\n}")
        self.btn_signup.setObjectName("btn_signup")
        self.btn_login = QtWidgets.QPushButton(parent=self.frame)
        self.btn_login.setGeometry(QtCore.QRect(470, 570, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_login.setFont(font)
        self.btn_login.setStyleSheet(
            "QPushButton{\n"
            "\n"
            "    background-color:rgba(63,64,66,255);\n"
            "border:2px solid black;\n"
            "border-radius:10px;\n"
            "color:white;\n"
            "\n"
            "}\n"
            "QPushButton:hover{\n"
            "\n"
            "background-color:rgba(32,33,36,255);\n"
            "color:white;\n"
            "border:2px solid black;\n"
            "}"
        )
        self.btn_login.setObjectName("btn_login")
        self.email = QtWidgets.QLineEdit(parent=self.frame)
        self.email.setGeometry(QtCore.QRect(130, 310, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email.setFont(font)
        self.email.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding-left:10px;\n"
            "background-color: rgba(63,64,66,255)\n"
            "\n"
            "}"
        )
        self.email.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly)
        self.email.setClearButtonEnabled(True)
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(parent=self.frame)
        self.password.setGeometry(QtCore.QRect(130, 380, 500, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet(
            "QLineEdit{\n"
            "border-radius:10px;\n"
            "border:2px solid black;\n"
            "padding-left:10px;\n"
            "background-color: rgba(63,64,66,255)\n"
            "\n"
            "}"
        )
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Create Account"))
        self.username.setPlaceholderText(_translate("Form", "Username"))
        self.re_password.setPlaceholderText(_translate("Form", "Retype Password"))
        self.label_3.setText(_translate("Form", "Already Have Account?"))
        self.btn_signup.setText(_translate("Form", "Click Here"))
        self.btn_login.setText(_translate("Form", "Signup"))
        self.email.setPlaceholderText(
            _translate("Form", "example@securetech-cards.com")
        )
        self.password.setPlaceholderText(_translate("Form", "Password"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
