# Form implementation generated from reading ui file 'df.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1625, 900)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(0, 900))
        Dialog.setMaximumSize(QtCore.QSize(1625, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("../resources/stc_logo.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1066))
        self.frame.setStyleSheet("background-color: rgb(132, 132, 132);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setStyleSheet(
            "\n"
            "QTabBar:tab{\n"
            "width:110px;\n"
            "height:25px;\n"
            "color:rgb(216, 216, 216);\n"
            'font: 12pt "Segoe UI";\n'
            "border:none;\n"
            "margin-left:2px;\n"
            "margin-top:2px;\n"
            "margin-bottom:2px;\n"
            "padding:2px;\n"
            "color:black;\n"
            "background-color: rgb(206, 206, 206);\n"
            "}\n"
            "\n"
            " QTabBar:tab:!selected:hover{\n"
            "opacity:0.1;\n"
            "color: rgba(0,0,0);\n"
            "margin-top:2px;\n"
            "}\n"
            "QTabWidget QTabBar:tab:selected{\n"
            "color:black;\n"
            '    font: 700 11pt "Segoe UI";\n'
            "background-color: rgb(130, 130, 130);\n"
            "\n"
            "}\n"
            "QTabWidget QTabBar:tab:!selected{\n"
            "\n"
            "background-color: rgb(160, 160, 155);\n"
            "color: rgba(75, 75, 75, 100);\n"
            "}\n"
            "\n"
            "\n"
            "QTabWidget QTabBar:tab:selected:hover{\n"
            "\n"
            "\n"
            "}"
        )
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_electrical_data = QtWidgets.QWidget()
        self.tab_electrical_data.setObjectName("tab_electrical_data")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_electrical_data)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.tab_electrical_data)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.elect_tableWidget = QtWidgets.QTableWidget(parent=self.frame_2)
        self.elect_tableWidget.setStyleSheet(
            "QTableWidget{\n"
            "color:black;\n"
            "            background: white;\n"
            "selection-background-color:#0090c4;\n"
            "border:none;\n"
            " gridline-color:black;\n"
            "border-left:1px solid black;\n"
            "border-right:1px solid black;\n"
            "}\n"
            "QComboBox{\n"
            "    border:                 none;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "color:                      rgb(13, 13, 13);\n"
            "    font-weight:            bold;\n"
            "    padding:                    5px;\n"
            "\n"
            "}\n"
            "QComboBox:selected{\n"
            "   \n"
            "    background-color: rgb(0, 144, 196);\n"
            "color:                      rgb(13, 13, 13);\n"
            "}\n"
            "\n"
            "QHeaderView{\n"
            "    \n"
            "    background-color: rgb(255, 255, 255);\n"
            '    font: 700 9pt "Segoe UI";\n'
            "}\n"
            "QHeaderView::section{\n"
            "background-color: rgb(220, 220, 220);\n"
            "border:0.5px solid black;\n"
            "border-left:none;\n"
            "}"
        )
        self.elect_tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.elect_tableWidget.setAlternatingRowColors(True)
        self.elect_tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.elect_tableWidget.setShowGrid(True)
        self.elect_tableWidget.setWordWrap(True)
        self.elect_tableWidget.setCornerButtonEnabled(True)
        self.elect_tableWidget.setRowCount(25)
        self.elect_tableWidget.setColumnCount(14)
        self.elect_tableWidget.setObjectName("elect_tableWidget")
        self.elect_tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.elect_tableWidget.verticalHeader().setVisible(False)
        self.elect_tableWidget.verticalHeader().setHighlightSections(True)
        self.elect_tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_4.addWidget(self.elect_tableWidget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_electrical_data, "")
        self.tab_graphical_data = QtWidgets.QWidget()
        self.tab_graphical_data.setObjectName("tab_graphical_data")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_graphical_data)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_3 = QtWidgets.QFrame(parent=self.tab_graphical_data)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.graph_tableWidget = QtWidgets.QTableWidget(parent=self.frame_3)
        self.graph_tableWidget.setStyleSheet(
            "QTableWidget{\n"
            "color:black;\n"
            "            background: white;\n"
            "selection-background-color:#0090c4;\n"
            "border:none;\n"
            " gridline-color:black;\n"
            "border-left:1px solid black;\n"
            "border-right:1px solid black;\n"
            "}\n"
            "QComboBox{\n"
            "    border:                 none;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "color:                      rgb(13, 13, 13);\n"
            "    font-weight:            bold;\n"
            " \n"
            "\n"
            "}\n"
            "QComboBox:selected{\n"
            "   \n"
            "    background-color: rgb(0, 144, 196);\n"
            "color:                      rgb(13, 13, 13);\n"
            "}\n"
            "\n"
            "QHeaderView{\n"
            "    \n"
            "    background-color: rgb(255, 255, 255);\n"
            '    font: 700 9pt "Segoe UI";\n'
            "}\n"
            "QHeaderView::section{\n"
            "background-color: rgb(220, 220, 220);\n"
            "border:0.5px solid black;\n"
            "border-left:none;\n"
            "}"
        )
        self.graph_tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.graph_tableWidget.setAlternatingRowColors(True)
        self.graph_tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.graph_tableWidget.setRowCount(10)
        self.graph_tableWidget.setColumnCount(14)
        self.graph_tableWidget.setObjectName("graph_tableWidget")
        self.graph_tableWidget.verticalHeader().setVisible(False)
        self.graph_tableWidget.verticalHeader().setHighlightSections(True)
        self.gridLayout_6.addWidget(self.graph_tableWidget, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_graphical_data, "")
        self.tab_server_data = QtWidgets.QWidget()
        self.tab_server_data.setObjectName("tab_server_data")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_server_data)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(parent=self.tab_server_data)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.server_tableWidget = QtWidgets.QTableWidget(parent=self.frame_4)
        self.server_tableWidget.setStyleSheet(
            "QTableWidget{\n"
            "color:black;\n"
            "            background: white;\n"
            "selection-background-color:#0090c4;\n"
            "border:none;\n"
            " gridline-color:black;\n"
            "border-left:1px solid black;\n"
            "border-right:1px solid black;\n"
            "}\n"
            "QComboBox{\n"
            "    border:                 none;\n"
            "    background-color: rgb(255, 255, 255);\n"
            "color:                      rgb(13, 13, 13);\n"
            "    font-weight:            bold;\n"
            " \n"
            "\n"
            "}\n"
            "QComboBox:selected{\n"
            "   \n"
            "    background-color: rgb(0, 144, 196);\n"
            "color:                      rgb(13, 13, 13);\n"
            "}\n"
            "\n"
            "QHeaderView{\n"
            "    \n"
            "    background-color: rgb(255, 255, 255);\n"
            '    font: 700 9pt "Segoe UI";\n'
            "}\n"
            "QHeaderView::section{\n"
            "background-color: rgb(220, 220, 220);\n"
            "border:0.5px solid black;\n"
            "border-left:none;\n"
            "}"
        )
        self.server_tableWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.server_tableWidget.setAlternatingRowColors(True)
        self.server_tableWidget.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.server_tableWidget.setRowCount(25)
        self.server_tableWidget.setColumnCount(14)
        self.server_tableWidget.setObjectName("server_tableWidget")
        self.server_tableWidget.verticalHeader().setVisible(False)
        self.server_tableWidget.verticalHeader().setHighlightSections(True)
        self.gridLayout_8.addWidget(self.server_tableWidget, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_server_data, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            55,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Maximum,
        )
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Secure Tech Cards (Pvt) Ltd."))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_electrical_data),
            _translate("Dialog", "Electrical Data"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_graphical_data),
            _translate("Dialog", "Graphical Data"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_server_data),
            _translate("Dialog", "Server Data"),
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
